{
  "$schema": "https://raw.githubusercontent.com/earendil-works/pi/main/packages/coding-agent/src/modes/interactive/theme/theme-schema.json",
  "name": "current",
  "colors": {
    "accent": "{{ accent }}",
    "border": "{{ color8 }}",
    "borderAccent": "{{ accent }}",
    "borderMuted": "{{ color0 }}",
    "success": "{{ color2 }}",
    "error": "{{ color1 }}",
    "warning": "{{ color3 }}",
    "muted": "{{ color8 }}",
    "dim": "{{ color8 }}",
    "text": "",
    "thinkingText": "{{ color8 }}",
    "selectedBg": "{{ color0 }}",
    "userMessageBg": "{{ color0 }}",
    "userMessageText": "",
    "customMessageBg": "{{ color0 }}",
    "customMessageText": "",
    "customMessageLabel": "{{ accent }}",
    "toolPendingBg": "{{ color0 }}",
    "toolSuccessBg": "{{ mix(color2, background, 5) }}",
    "toolErrorBg": "{{ mix(color1, background, 5) }}",
    "toolTitle": "{{ accent }}",
    "toolOutput": "",
    "mdHeading": "{{ color3 }}",
    "mdLink": "{{ accent }}",
    "mdLinkUrl": "{{ color8 }}",
    "mdCode": "{{ color6 }}",
    "mdCodeBlock": "",
    "mdCodeBlockBorder": "{{ color8 }}",
    "mdQuote": "{{ color8 }}",
    "mdQuoteBorder": "{{ color8 }}",
    "mdHr": "{{ color8 }}",
    "mdListBullet": "{{ color6 }}",
    "toolDiffAdded": "{{ color2 }}",
    "toolDiffRemoved": "{{ color1 }}",
    "toolDiffContext": "{{ color8 }}",
    "syntaxComment": "{{ color8 }}",
    "syntaxKeyword": "{{ accent }}",
    "syntaxFunction": "{{ color6 }}",
    "syntaxVariable": "{{ color3 }}",
    "syntaxString": "{{ color2 }}",
    "syntaxNumber": "{{ color5 }}",
    "syntaxType": "{{ accent }}",
    "syntaxOperator": "{{ accent }}",
    "syntaxPunctuation": "{{ color8 }}",
    "thinkingOff": "{{ color8 }}",
    "thinkingMinimal": "{{ accent }}",
    "thinkingLow": "{{ color6 }}",
    "thinkingMedium": "{{ color14 }}",
    "thinkingHigh": "{{ color5 }}",
    "thinkingXhigh": "{{ color1 }}",
    "bashMode": "{{ color3 }}"
  }
}
